declare const __DEV__: boolean;
declare const __TEST__: boolean;
declare function require(module: string): any;

declare module 'lucide-react-native' {
  const Icon: (props: any) => any;
  export default Icon;
  
  // الأيقونات الأساسية
  export const Calendar: any; export const Heart: any; export const Sparkles: any;
  export const Clock: any; export const X: any; export const Home: any;
  export const Lightbulb: any; export const Thermometer: any; export const Music: any;
  export const Wifi: any; export const Power: any; export const Brain: any;
  export const Shield: any; export const FileText: any; export const Mail: any;
  export const Globe: any; export const AlertTriangle: any; export const Gift: any;
  export const Copy: any; export const Share2: any; export const Users: any;
  export const User: any; export const UserPlus: any; export const Star: any;
  export const BookOpen: any; export const Code: any; export const Briefcase: any;
  export const PenTool: any; export const Sun: any;
  export const Moon: any; export const CheckSquare: any;
  export const Image: any; export const Terminal: any; export const Bug: any;
  export const GitBranch: any; export const Rocket: any; export const ChevronRight: any;
  export const MessageCircle: any; export const Target: any; export const Link: any;
  export const Share: any; export const Alert: any; export const ActivityIndicator: any;
  export const Chrome: any; export const Eye: any; export const EyeOff: any;
  export const Send: any; export const Mic: any; export const MicOff: any;
  export const Play: any; export const BatteryCharging: any; export const Zap: any;
  export const AlertCircle: any; export const MessageSquare: any; export const RefreshCw: any;
  export const Palette: any; export const Wand2: any; export const Search: any;
  export const Camera: any; export const TrendingUp: any; export const BarChart3: any;
  export const DollarSign: any; export const Edit3: any; export const Bell: any;
  export const TreePine: any; export const Grid3X3: any; export const Settings: any;
  export const Info: any; export const HelpCircle: any; export const Crown: any;
  export const BatteryFull: any; export const BatteryWarning: any; export const Plus: any;
  export const ListChecks: any; export const ArrowRight: any; export const Volume2: any;
  export const Database: any; export const Languages: any; export const Activity: any;
  export const CheckCircle2: any;
  
  // الأيقونات المفقودة (إضافات جديدة)
  export const Cloud: any;
  export const Filter: any;
  export const Compass: any;
  export const Crosshair: any;
  export const Wallet: any;
  export const MapPin: any;
  export const Download: any;
  export const RotateCcw: any;
  export const Award: any;
  export const Smartphone: any;
  export const LogOut: any;
  export const Battery: any;
  export const Zap: any;
  export const Star: any;
  export const Crown: any;
  export const CheckCircle2: any;
  export const ArrowRight: any;
  export const RefreshCw: any;
  export const Play: any;
  export const Gift: any;
  export const TrendingUp: any;
  export const BatteryWarning: any;
  export const BatteryFull: any;
  export const Lightbulb: any;
  export const Heart: any;
  export const Brain: any;
  export const Clock: any;
  export const Activity: any;
  export const Mail: any;
  export const Shield: any;
  export const User: any;
  export const HelpCircle: any;
  export const RotateCw: any;
  export const MessageCircle: any;
  export const X: any;
  export const Grid3X3: any;
  export const Settings: any;
  export const Info: any;
  export const Crown: any;
  export const Bell: any;
  export const Sparkles: any;
  export const Globe: any;
  export const Sun: any;
  export const Moon: any;
  export const Volume2: any;
  export const Database: any;
  export const Languages: any;
  export const CheckSquare: any;
  export const Plus: any;
  export const Calendar: any;
  export const Target: any;
  export const ChevronRight: any;
  export const BookOpen: any;
  export const Briefcase: any;
  export const Code: any;
  export const Heart: any;
  export const Palette: any;
  export const Search: any;
  export const Camera: any;
  export const Wand2: any;
  export const TrendingUp: any;
  export const BarChart3: any;
  export const DollarSign: any;
  export const Rocket: any;
  export const Shield: any;
  export const PenTool: any;
  export const Edit3: any;
  export const MessageSquare: any;
  export const MessageCircle: any;
  export const BookOpen: any;
  export const Camera: any;
  export const Calendar: any;
  export const Clock: any;
  export const MapPin: any;
  export const Heart: any;
  export const Star: any;
  export const Zap: any;
  export const Cloud: any;
  export const HelpCircle: any;
  export const RefreshCw: any;
  export const Download: any;
  export const AlertTriangle: any;
  export const RotateCcw: any;
  export const RotateCw: any;
  export const MessageCircle: any;
  export const Mail: any;
  export const Activity: any;
  export const Clock: any;
  export const MapPin: any;
  export const TrendingUp: any;
  export const Heart: any;
  export const User: any;
  export const Mail: any;
  export const Shield: any;
  export const Cloud: any;
  export const Smartphone: any;
  export const LogOut: any;
  export const Crown: any;
  export const Star: any;
  export const CheckCircle2: any;
  export const Brain: any;
  export const Zap: any;
  export const Sparkles: any;
  export const ArrowRight: any;
  export const RefreshCw: any;
  export const Play: any;
  export const Gift: any;
  export const TrendingUp: any;
  export const Battery: any;
  export const BatteryWarning: any;
  export const BatteryFull: any;
  export const Brain: any;
  export const Eye: any;
  export const Heart: any;
  export const TrendingUp: any;
  export const Lightbulb: any;
  export const CheckSquare: any;
  export const Plus: any;
  export const Calendar: any;
  export const Clock: any;
  export const TrendingUp: any;
  export const Target: any;
  export const ListChecks: any;
  export const ChevronRight: any;
  export const Brain: any;
  export const BookOpen: any;
  export const Briefcase: any;
  export const Sun: any;
  export const Moon: any;
  export const Palette: any;
  export const Heart: any;
  export const Code: any;
}

declare module 'expo-clipboard' {
  export function setStringAsync(text: string): Promise<void>;
  export function getStringAsync(): Promise<string>;
}

declare module '*.mp3' { const value: number; export default value; }
declare module '*.png' { const value: number; export default value; }
declare module '*.jpg' { const value: number; export default value; }
